<a href="https://colab.research.google.com/github/mithun-martin/PYTORCH_TUTORIALS/blob/main/1_PYTORCH_TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model,
as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.
If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along in this quick API walkthrough.

In [ ]:
import torch
import numpy as np

Tensor Initialization
Tensors can be initialized in various ways. Take a look at the following examples:



**1.Directly from data**  

torch.tensor(data)

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**2.From a NumPy array**   
 torch.from_numpy(np_array)

In [ ]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


### Difference 1: Math Behavior
Watch what happens when we try to multiply our data structures by 2.

In [ ]:
# Python list duplicates elements
print("List * 2:", data * 2)

# NumPy array and PyTorch Tensor perform element-wise multiplication
print("NumPy * 2:\n", np_array * 2)
print("Tensor * 2:\n", x_data * 2)

List * 2: [[1, 2], [3, 4], [1, 2], [3, 4]]
NumPy * 2:
 [[2 4]
 [6 8]]
Tensor * 2:
 tensor([[2, 4],
        [6, 8]])


### Difference 2: Device (CPU vs GPU)
Tensors can be sent to other processors (like a GPU) to run parallel calculations instantly.

In [ ]:
# Check if GPU is available
if torch.cuda.is_available():
    gpu_tensor = x_data.to('cuda')
    print("Tensor moved to GPU:", gpu_tensor)
    print("Device:", gpu_tensor.device)
else:
    print("Currently running on CPU device:", x_data.device)
    print("(You can enable GPUs in Colab via Edit -> Notebook settings)")

Tensor moved to GPU: tensor([[1, 2],
        [3, 4]], device='cuda:0')
Device: cuda:0


**3.From another tensor:**

In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4430, 0.1020],
        [0.1073, 0.0988]])


**4.With random or constant values:PROVIDING JUST SHAPE**

In [ ]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Ones Tensor: \n {zero_tensor} \n")

Random Tensor: 
 tensor([[0.9654, 0.1909, 0.7441],
        [0.3998, 0.4051, 0.1587]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Ones Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



***Tensor Attributes***

In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Tensor Operations**

In [ ]:
# We move our tensor to the GPU if available

In [ ]:
if torch.accelerator.is_available():
  device = torch.accelerator.current_accelerator().type
else:
  'cpu'
tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


**Standard numpy-like indexing and slicing:**

In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**

You can use torch.cat to concatenate a sequence of tensors along a given dimension.

dim=0: Concatenates vertically (top-to-bottom). It stacks rows on top of each other. The number of rows increases

dim=1: Concatenates horizontally (left-to-right). It places columns next to each other. The number of columns increases.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print("Vertically Concatenated (dim=0) Shape:", t2.shape)
print(t2)


Vertically Concatenated (dim=0) Shape: torch.Size([12, 4])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Multiplying tensors**

In [ ]:
a = tensor * tensor
print (a)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# matrix multiplication between two tensors
a = rand_tensor.matmul(zero_tensor.T)
print(a)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
#In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.
print(tensor, "\n")
tensor.add_(5)
print(tensor)



tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


**Tensor to NumPy array**

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


**NumPy array to Tensor**

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)